language: node_js
node_js:
- lts/*
before_install:
- curl -L https://foundry.paradigm.xyz | bash
- foundryup
install:
- npm install
script:
- npm run lint
- npm run lint-contracts
- forge build
- forge test -vv
